server:
  port: 28083

genefile:
  javafilePath: src/main/java
  resourcePath: src/main/resources
  mapperPackage: com.sss.web.mapper
  mapperExtPath: src/main/resources/mapper
  templateDirName: ${genefile.resourcePath}/templates

  servicePackage: com.sss.web.service
  baseServicePackage: com.sss.ormbase.common.service
  entityPackage: com.sss.ormbase.autogenerate.model

  controllerPackage: com.sss.web.controller

  generateFiles:
    - ormName: Department
      # table name
      tableName: department
      create: CreateDepartment
      update: UpdateDepartment
      delete: DeleteDepartment
      list: ListDepartment
      protoObjName: DepartmentItem
      requestMapping: /department
